#!/bin/sh
# xfilesctl -- XFiles control script
#
# This file is called by xfiles(1) upon user interaction.
#
# When invoked, XFiles waits for this script to exit.  Therefore, if
# this script does something that takes too much time to return, the
# XFiles window will become unresponsive.
#
# If this script calls a program that may take some time, you should
# do it asynchronously by ending the command with an ampersand (&).
#
# This script depends on the following programs:
# - $OPENER (defaults to xdg-open) for opening files.
# - $EDITOR (defaults to vi) for editing text files.
# - xmessage, for displaying dialogs.
# - xterm, for opening the text editor.
# - xmenu, for popping up a mouse-based menu.
# - dmenu, for popping up a keyboard-based menu.
# - xclip, for setting the clipboard.
# - xprop, for setting window properties.
# - File management core utilities (rm, mkdir, mv, cp, etc).
# - Sed and AWK.

# set this to false to not open dialogs asking for confirmation
ask=true
#ask=false

# default paths
TRASH="${TRASH:-"${XDG_DATA_HOME:-"$HOME/.local/share"}/Trash"}"

# default commands
OPENER="${OPENER:-"xdg-open"}"
EDITOR="${EDITOR:-"${VISUAL:-"vi"}"}"

# ADDED files
LOG_PREV_DIR="/tmp/${USER}-xfilesctl-prev-dir.log"
# works form keyboard, TODO: also add mouse
LOG_PREVS_DIRS="/tmp/${USER}-xfilesctl-prevs-dir.log"
LOG_CUSTOM_DIR="/tmp/${USER}-xfilesctl-custom-dir.log"
# history of $LOG_PREVS_DIRS
MAX_PREVS_DIRS=50

# custom dmenu
_dmenu() {
  dmenu -i -w "$WINDOWID" \
        -nf '#BBBBBB' -nb '#2B2B2B' \
        -sf '#BBBBBB' -sb '#113A5C' \
        -fn 'DejaVu Sans Mono:pixelsize=14:antialias=true:autohint=true' \
        "$@"
}

_dmenusel() {
  dmenu -i -w "$WINDOWID" \
        -nf '#BBBBBB' -nb '#373737' \
        -sf '#000000' -sb '#9eeeee' \
        -fn 'DejaVu Sans Mono:pixelsize=14:antialias=true:autohint=true' \
        "$@"
}

_dmenuerr() {
  dmenu -w "$WINDOWID" \
        -nf '#BBBBBB' -nb '#373737' \
        -sf '#FFFFFF' -sb '#FF0000' \
        -fn 'DejaVu Sans Mono:pixelsize=14:antialias=true:autohint=true'
}

# print error message
warn() {
	printf '%s: %s\n' "${0##*/}" "$*" >&2
}

# print error message and exit
err() {
	warn "$@"
	exit 1
}

# open mouse-based menu containing entries from stdin
menu() {
	xmenu
}

# open keyboard-based menu containing entries from stdin
prompt() {
	# dmenu -w "$WINDOWID"
  # MODIFIED
  # same background
  # -nb "#2B2B2B"
	# dmenu -i -w "$WINDOWID" \
  #       -nf "#BBBBBB" \
  #       -nb "#373737" \
  #       -sf "#000000" \
  #       -sb "#9eeeee" \
  #       -fn "DejaVu Sans Mono:pixelsize=14:antialias=true:autohint=true" \
  #       -p '>' \
  #       -l 15
  _dmenusel -p "$(basename "${PWD}")/" -l 25
}


# open new xfiles window on current directory
newwin() {
	xfiles &
}

# open terminal window running given command
term() {
	xterm &
}

# checks if the program needs a terminal emulator
withterm() {
  program="$1"
  nongui="gorum less lynx man more mpv mplayer nvi vi vim"
  for prg in $nongui; do
    if [ "$prg" = "$program" ]; then
      return 1
    fi
  done
  return 0
}

# open given files (on background, so xfiles not wait)
open() {
	command -- "$OPENER" "$@" &
}

# open given files with a custom program (on background, so xfiles not wait)
openwith() {
  args="$*"
  msg="press Esc or Enter to exit"
  prgfull=$(echo "$msg" | _dmenu -p "Open file '${args}' with:")
  # empty or Esc/Enter
  if [ -z "$prgfull" ] || [ "$prgfull" = "$msg" ]; then
    return
  fi
  prgbase=$(echo "$prgfull" | cut -d ' ' -f1)
  if ! command -v "$prgbase" >/dev/null 2>&1; then
    echo "error: program '${prgbase}' is missing" | _dmenuerr
    exit 1
  fi
  if ! withterm "$prgbase"; then
	  command -- xterm -e "$prgfull '${args}'" &
  else
	  eval command -- "$prgfull" "'${args}'" &
	fi
}

# check the output of different mime tools
checkmime() {
  xdgout=$(xdg-mime query filetype "$*")
  xdgprg=$(xdg-mime query default "$xdgout")
  mimeout=$(mimetype --brief "$*")
  mimeprg=$(xdg-mime query default "$mimeout")
  fileout=$(file --brief --mime-type "$*")
  fileprg=$(xdg-mime query default "$fileout")
  # if [ "$xdgout" = "$mimeout" ] && [ "$mimeout" = "$fileout" ]; then
  if [ "$xdgprg" = "$mimeprg" ] && [ "$mimeprg" = "$fileprg" ]; then
	  # shellcheck disable=SC2028
    #echo "ok: mime types for '${*}' are equal\nxdg-mime: '${xdgout}' {${xdgprg}}\nmimetype: '${mimeout}' {${mimeprg}}\nfile:     '${fileout}' {${fileprg}}" | dmenu -l 4
    echo "ok: mime program default for '${*}' are equal\nxdg-mime: '${xdgout}' {${xdgprg}}\nmimetype: '${mimeout}' {${mimeprg}}\nfile:     '${fileout}' {${fileprg}}" | _dmenu -l 4
  else
	  # shellcheck disable=SC2028
    #echo "error: mime types for '${*}' are different\nxdg-mime: '${xdgout}' {${xdgprg}}\nmimetype: '${mimeout}' {${mimeprg}}\nfile:     '${fileout}' {${fileprg}}" | dmenu -l 4
    echo "error: mime program default for '${*}' are different\nxdg-mime: '${xdgout}' {${xdgprg}}\nmimetype: '${mimeout}' {${mimeprg}}\nfile:     '${fileout}' {${fileprg}}" | _dmenu -l 4
    exit 1
  fi
}

# set mime type (see ~/.config/mimeapps.list, ~/.local/share/applications/mime* etc)
setmime() {
  # xdg-mime and file returns differnts mime types
  kind="$1"
  shift
  if [ "$kind" = "file" ]; then
    curmime=$(file --brief --mime-type "$*")
  elif [ "$kind" = "mimetype" ]; then
    curmime=$(mimetype --brief "$*")
  else
    curmime=$(xdg-mime query filetype "$*")
  fi
  if [ -z "$curmime" ]; then
    echo "error: filetype '${*}' does not have a valid mime" | _dmenuerr
    exit 1
  fi
  defprgmime=$(xdg-mime query default "$curmime")
  msg="press Esc or Enter to exit"
  newprg=$(echo "$msg" | _dmenu -p "Set default mime type '${curmime}' {${defprgmime}} to program:")
  # empty or Esc/Enter
  if [ -z "$newprg" ] || [ "$newprg" = "$msg" ]; then
    return
  fi
  mimepaths="/usr/share/applications /usr/local/share/applications ${HOME}/.local/share/applications"
	# shellcheck disable=SC2086
  if ! find $mimepaths -name '*.desktop' -print 2>/dev/null | grep -qE "/?${newprg}.desktop$"; then
    echo "error: mime type file '${newprg}.desktop' does not exist" | _dmenuerr
    exit 1
  fi
  xdg-mime default "${newprg}.desktop" "$curmime" &
}

# open text editor on given file
edit() {
  #xterm -into "$WINDOWID" -bw 0 -e "$EDITOR" -- "$@"
  if [ "$#" -ne 1 ]; then
    echo "error: only one file can be edited" | _dmenuerr
    exit 1
  fi
	gvim -f -- "$@"
}

# open dialog asking for confirmation ("$1" is the prompt, rest are filenames)
dialog() {
	"$ask" || return 0
	prompt="$1"
	shift 1
	#{
	#	printf "%s\n" "$prompt"
	#	printf "\t%s\n" "$@"
	#} | xmessage -buttons Yes:0,No:1 -nearmouse -file -
  if [ "$(printf 'no\nyes' | _dmenu -p "$prompt ${*}")" = "yes" ]; then
    return 0
  fi
  return 1
}

# if $1 == /path/to/file_1.txt exists, set $uniquepath to /path/to/file_2.txt and so on
setuniquepath() {
	basename="${1##*/}"
	dirname="${1%/*}"
	body="${basename%.*}"
	ext="${basename##"$body"}"

	# create unique name
	unset -v i p
	while test -e "$dirname/$body$p$i$ext"; do
		p="_"
		if [ -z "$i" ]; then
			i=1
		else
			i=$((i + 1))
		fi
	done
	uniquepath="$dirname/$body$p$i$ext"
}

# copy files here if user confirms dialog
copy() {
	dialog "Copy files to $PWD?" "$@" && {
		for file; do
			setuniquepath "$PWD/${file##*/}"
			cp -v "$file" "$uniquepath"
		done
	}
}

# move files here if user confirms dialog
move() {
	dialog "Move files to $PWD?" "$@" && {
		for file; do
			setuniquepath "$PWD/${file##*/}"
			mv -v "$file" "$uniquepath"
		done
	}
}

# link files here if user confirms dialog
link() {
	dialog "Link files to $PWD?" "$@" && {
		for file; do
			setuniquepath "$PWD/${file##*/}"
			ln -s "$file" "$uniquepath"
		done
	}
}

# send files to trash if user confirms dialog
trash() {
	case $# in (0) return ;; esac
	dialog "Send files to trash?" "$@" || return
	# shellcheck disable=SC2174
	mkdir -m 700 -p -- "$TRASH/files" "$TRASH/info" || exit 1
	for file; do
		test -e "$file" || continue

		# get unique target
		setuniquepath "$TRASH/files/${file##*/}"

		# move file to trash and write trash information
		mv -- "$file" "$uniquepath" && \
		cat > "$TRASH/info/${uniquepath##*/}.trashinfo" <<-END
			[Trash Info]
			Path=$file
			DeletionDate=$(date +"%FT%H:%M:%S")
		END
	done
}

# find files on the selected directory
findfiles() {
  if [ "$#" -gt 1 ]; then
    echo "error: only one directory is allowed" | _dmenuerr
    exit 1
  elif [ "$#" -eq 1 ]; then
	  dirname="${1%/}"
	else
	  dirname="${PWD}"
  fi
  if [ ! -d "$dirname" ]; then
    echo "error: only directories can use find" | _dmenuerr
    exit 1
  fi
	if [ -z "$(ls -A "$dirname")" ]; then
    echo "error: the directory '$dirname' is empty" | _dmenuerr
    exit 1
	fi
	# entry=$(find "$dirname" -type f | dmenu -l 10)
	hidden=$([ -n "$XFILES_SHOW_HIDDEN" ] && [ "$XFILES_SHOW_HIDDEN" = 1 ] && echo "--hidden" || echo "")
	entry="${dirname}"/$(fd --base-directory "$dirname" "$hidden" | _dmenusel -p "$(basename "${dirname}")/" -l 25)
	entry="${entry%/}"
	if [ "$entry" = "$dirname" ]; then
	  return
	fi
	if [ -d "$entry" ]; then
		changedir "$entry"
	else
		open "$entry"
	fi
}

# restore files from trash if user confirms dialog
untrash() {
	case $# in (0) return ;; esac

	# compose dialog message
	msg="Restore files from trash?"
	for file; do
		shift
		basename="${file##*/}"
		infofile="$TRASH/info/$basename.trashinfo"
		origfile="$(sed -En '/^[[:blank:]]*Path[[:blank:]]*=/{s/.*=[[:blank:]]*//;p;q;}' < "$infofile")"
		if test -e "$origfile"; then
			warn "$basename: file already exists on original directory"
		else
			set -- "$file" "$origfile" "$infofile"
			msg="$msg
	$origfile"
		fi
	done

	dialog "$msg" || return

	while test $# -gt 0; do
		file="$1"
		origfile="$2"
		infofile="$3"
		shift 3
		mv -- "$file" "$origfile" && rm -- "$infofile"
	done
}

# rm file if user confirms dialog (if at trash, also remove info file)
delete() {
	dialog "Delete files permanently?" "$@" || return
	rm -rf -- "$@"
	case "$PWD" in
	("$TRASH/files")
		for file; do
			rm -rf -- "$TRASH/info/${file##*/}.trashinfo"
		done
		;;
	esac
}

# delete all files in trash can (directory)
emptytrash() {
	dialog "Empty trash?" || return
	rm -rf "$TRASH/files/"*
	rm -rf "$TRASH/info/"*
}

# save file paths into clipboard
snarf() {
	case "$#" in
	(0)
		# no file to copy
		return
		;;
	esac
	# send URIs to clipboard
	# printf 'file://%s\r\n' "$@" |\
	# xclip -selection clipboard -in -target "text/uri-list" &
	# modified as is not pasted always if text/uri-list does not exist
	printf 'file://%s\n' "$@" |\
	xclip -selection clipboard &
}

# paste file whose paths are on clipboard
paste() {
	cmd="$1"
	shift 1
	{
		# get URIs from clipboard
		xclip -selection clipboard -out -target "text/uri-list"
		echo
	} | sed 's,^file://,,' | tr -d '\r' | {
		set --
		while read -r f; do
			case "$f" in
			("")
				;;
			(*)
				set -- "$@" "$f"
				;;
			esac
		done
		case "$cmd" in
		("cp")
			copy "$@"
			;;
		("mv")
			move "$@"
			;;
		("ln")
			link "$@"
			;;
		esac
	}
}

# rename files in text editor
#rename() {
#	case "$#" in (0) return ;; esac
#
#	unset -v tempfile tempdir TMPDIR
#	trap '
#		test "$tempfile" && rm -f -- "$tempfile" 2>/dev/null
#		test "$tempdir" && rmdir -- "$tempdir" 2>/dev/null
#		exit
#	' EXIT HUP
#	tempfile="$(mktemp)" || exit 1
#	tempdir="$(mktemp -d -p "$PWD")" || exit 1
#
#	for file
#	do
#		file="${file#"$PWD/"}"
#		case "$file" in
#		("")
#			err "empty argument"
#			;;
#		(*[[:cntrl:]]*)
#			err "renaming files containing control characters is not supported"
#			;;
#		([[:space:]]*|*[[:space:]])
#			err "renaming files beginning or ending in space is not supported"
#			;;
#		esac
#		printf "%s\n" "$file" >> "$tempfile"
#	done
#
#	edit "$tempfile" || exit 1
#
#	mv -- "$@" "$tempdir" || exit 1
#	while read -r target
#	do
#		source="$tempdir/${1##*/}"
#		if test -z "$target"
#		then
#			trash "$source"
#		else
#			case "$target" in
#			(*/*)
#				mkdir -p "${target%/*}"
#				;;
#			esac
#			case "$target" in
#			(/*|./*|../*)
#				;;
#			(*)
#				target="$PWD/$target"
#				;;
#			esac
#			setuniquepath "$target"
#			mv -- "$source" "$uniquepath"
#		fi
#		shift
#	done <"$tempfile"
#	{
#		mv -- "$tempdir/"* ./
#		rmdir -- "$tempdir"
#		rm -f -- "$tempfile"
#	} 2>/dev/null
#}

# rename files in text editor
rename() {
  if [ "$#" -ne 1 ]; then
    echo "error: only one file can be renamed" | _dmenuerr
    exit 1
  fi
  curname="$(basename "$@")"
  msg="press Esc or Enter to exit"
  newname=$(echo "$msg" | _dmenu -p "Rename '${curname}' to:")
  # empty or Esc/Enter
  if [ -z "$newname" ] || [ "$newname" = "$msg" ]; then
    return
  fi
	if [ "$curname" = "$newname" ]; then
    echo "error: current file '${curname}' and the new file '${newname}' have the same name" | _dmenuerr
    exit 1
  fi
	if [ -e "$newname" ]; then
    echo "error: file or directory '${newname}' alredy exists" | _dmenuerr
    exit 1
  fi
  mv -v -- "$curname" "$newname"
}

# create directories named on text editor
#makedir() {
#	unset -v tempfile
#	trap 'test "$tempfile" && rm -f -- "$tempfile" 2>/dev/null' EXIT
#	tempfile="$(mktemp)" || exit 1
#	edit "$tempfile"
#	while read -r dir
#	do
#		mkdir -p "$dir"
#	done <"$tempfile"
#	rm "$tempfile"
#}

# create a directory named on text editor
makedir() {
  msg="press Esc or Enter to exit"
  newdir=$(echo "$msg" | _dmenu -p "New directory:")
  # empty or Esc/Enter
  if [ -z "$newdir" ] || [ "$newdir" = "$msg" ]; then
    return
  fi
	if [ -e "$newdir" ]; then
    echo "error: file or directory '${newdir}' alredy exists" | _dmenuerr
    exit 1
  fi
  mkdir -v -p "$newdir"
}

# create a file named on text editor
makefile() {
  if [ "$#" -eq 0 ]; then
    echo "error: missing argument" | _dmenuerr
    exit 1
  elif [ "$#" -ne 1 ]; then
    echo "error: only one file can be created" | _dmenuerr
    exit 1
  fi
	cmd="$1"
	shift 1
  msg="press Esc or Enter to exit"
  newfile=$(echo "$msg" | _dmenu -p "New file ($cmd):")
  # empty or Esc/Enter
  if [ -z "$newfile" ] || [ "$newfile" = "$msg" ]; then
    return
  fi
	if [ -e "$newfile" ]; then
    echo "error: file or directory '${newfile}' alredy exists" | _dmenuerr
    exit 1
  fi
	if [ "$cmd" = "empty" ]; then
	  touch "$newfile"
	elif [ "$cmd" = "edit" ]; then
    edit "$newfile"
	fi
}

# open random file in current directory
#random() {
#	set --
#	for file in *
#	do
#		test -f "$file" && set -- "$file" "$@"
#	done
#	case "$#" in
#	(0)
#		return
#		;;
#	(*)
#		shift "$(awk 'BEGIN{print int(ARGV[1]*rand())}' "$#")"
#		open "$1"
#		;;
#	esac
#}

# change current directory of XFiles window
changedir() {
  # ADDED
  oldpwd="${LOG_PREV_DIR}"
  if [ -e "$oldpwd" ] && [ "$PWD" != "$(cat "$oldpwd")" ] && [ "$PWD" != "/" ] || [ ! -e "$oldpwd" ]; then
    echo "$PWD" > "$oldpwd"
  fi
	xprop -id "$WINDOWID" -format "_CONTROL_GOTO" 8u -set "_CONTROL_GOTO" "$1"
}

# prompt for file to open or directory to go to
urlbar() {
	# printf '%s\n' * | prompt | {
	if [ -n "$XFILES_SHOW_HIDDEN" ] && [ "$XFILES_SHOW_HIDDEN" = 1 ]; then
    files="$({
      fd --max-depth 1 --type d;
      fd '^\.' --max-depth 1 --type d --hidden;
      fd --max-depth 1 --type l;
      fd '^\.' --max-depth 1 --type l --hidden;
      fd --max-depth 1 --type f "$hidden";
      fd '^\.' --max-depth 1 --type f --hidden;
    })"
  else
    files="$({
      fd --max-depth 1 --type d;
      fd --max-depth 1 --type l;
      fd --max-depth 1 --type f;
    })"
  fi
	echo "$files" | prompt | {
		read -r entry
	  if [ -z "$entry" ]; then
	    return
	  fi
		if [ -d "$entry" ]; then
			changedir "$entry"
		else
			open "$entry"
		fi
	}
}

# pop-up menu for file dropping
dropmenu() {
	{
		cat <<-EOF
		copy
		move
		link
		none
		EOF
	} | menu | {
		read -r option
		case "$option" in
		("copy")
			copy "$@"
			;;
		("move")
			move "$@"
			;;
		("link")
			link "$@"
			;;
		("term")
			term
			;;
		esac
	}
}

# context menu for no selection
dirmenu() {
	{
	# random
		cat <<EOF
new file (empty)
new file (edit)
new directory
refresh
toggle hidden
find ($(basename "$PWD"))
go
	go home
	go up
	go prev
	go next (broken)
	go gitroot
	go trash (dir)
paste
	copy
	move
	link
open
	xfiles
	term
	tmux (xterm)
	tmux (alacritty)
$(
  case "$PWD" in ("$TRASH/files")
    # only if non-empty directory
    # if [ "$(ls -A "$TRASH/files")" ]; then
    #   printf 'empty trash'
    # fi
    printf 'empty trash'
    ;;
  (*)
    # printf 'trash can'
    printf 'trash (dir)'
    ;;
  esac
)
EOF
	} | menu | {
		read -r option
		case "$option" in

		("toggle hidden")
			xdotool key --clearmodifiers ctrl+period &
			;;
		("new directory")
			makedir
			;;
		("new file (empty)")
			makefile "empty"
			;;
		("new file (edit)")
			makefile "edit"
			;;
	  ("find ($(basename "$PWD"))")
		  # if [ "$PWD" = "$HOME" ]; then
	    #   if dialog "Find files to ${PWD}?"; then
		  #     findfiles "$@"
		  #   fi
		  # else
		  #   findfiles "$@"
		  # fi
		  case "$PWD" in
		    "${HOME}"/* )
		      findfiles "$@"
		    ;;
		  *)
	      if dialog "Find files to ${PWD}?"; then
		      findfiles "$@"
		    fi
		    ;;
		  esac
		  ;;
		("go up")
			changedir ".."
			;;
		("go home")
			changedir "$HOME"
			;;
		("go prev")
			#changedir "-"
      # changedir "$(test -f "${LOG_PREV_DIR}" && cat "${LOG_PREV_DIR}" || echo "$HOME")"
      if [ -f "${LOG_PREV_DIR}" ]; then
        changedir "$(cat "${LOG_PREV_DIR}")"
      fi
			;;
		("go next")
			changedir "+"
			;;
		("go gitroot")
      groot="$(git rev-parse --show-toplevel)"
      if [ -d "$groot" ]; then
        changedir "$groot"
      fi
			;;
		("go trash (dir)")
			changedir "$TRASH/files"
			;;
		("refresh")
			changedir "."
			;;
		("copy")
			paste "cp" "$@"
			;;
		("move")
			paste "mv" "$@"
			;;
		("link")
			paste "ln" "$@"
			;;
		("empty trash")
		  # only really empty
      # if [ "$(ls -A "$TRASH/files")" ]; then
			#   emptytrash
			# fi
			emptytrash
			;;
		# ("trash can")
		("trash (dir)")
			changedir "$TRASH/files"
			;;
		#("random")
		#	random
		#	;;
		("term")
			term
			;;
		("xfiles")
			newwin
			;;
		("tmux (xterm)")
		  xterm -u8 -class 'Scratchpad1' -e 'tmux new-session -A -D -s default' &
		  ;;
		("tmux (alacritty)")
		  alacritty --class 'Scratchpad1' &
		  ;;
		esac
	}
}

# context menu for selected files
filemenu() {
	case "$PWD" in
	("$TRASH/files")
		cat <<-EOF
		untrash
		delete
		EOF
		;;
	(*)
    # open {$(xdg-mime query default "$(xdg-mime query filetype "$*")" | sed 's/\.desktop$//')}
		# open {$(xdg-mime query default "$(mimetype --brief "$*")" | sed 's/\.desktop$//')}
    # open {$(xdg-mime query default "$(file --brief --mime-type "$*")" | sed 's/\.desktop$//')}
    # TODO: file and mimetype returns sometimes a different mime than xdg-mime
		cat <<-EOF
		open {$(xdg-mime query default "$(xdg-mime query filetype "$*")" | sed 's/\.desktop$//')}
		open (with)
		find ($(basename "$1"))
		set mime (xdg)
		set mime (mimetype)
		set mime (file)
		check mime
		rename
		snarf
		trash
		delete (dialog)
		EOF
		;;
	esac | menu | {
		read -r option
		case "$option" in
		("rename")
			rename "$@"
			;;
		("set mime (xdg)")
			setmime "xdg" "$1"
			;;
		("set mime (file)")
			setmime "file" "$1"
			;;
		("set mime (mimetype)")
			setmime "mimetype" "$1"
			;;
		("check mime")
			checkmime "$1"
			;;
		("snarf")
			snarf "$@"
			;;
		("delete")
			delete "$@"
			;;
		("delete (dialog)")
		  tmpask=$ask
		  ask=true
			delete "$@"
			ask=$tmpask
			;;
		("trash")
			trash "$@"
			;;
		("untrash")
			untrash "$@"
			;;
		#("open")
		("open {"*)
      if [ "$#" -ne 1 ]; then
        echo "error: only one file can be opened" | _dmenuerr
        exit 1
      fi
			open "$1"
			;;
		("open (with)")
      if [ "$#" -ne 1 ]; then
        echo "error: only one file can be opened" | _dmenuerr
        exit 1
      fi
			openwith "$1"
			;;
		("find ($(basename "$1"))")
		  findfiles "$@"
		  ;;
		esac
	}
}

# keys in the code widget.c
#    1. Navigation (Moving the Highlight)
#     These keys move the "focused" item (the one with the border/highlight).
#
#    * Up / k: Move highlight up one row.
#    * Down / j: Move highlight down one row.
#    * Left / h: Move highlight to the item on the left.
#    * Right / l: Move highlight to the item on the right.
#    * Home: Jump to the very first item (usually ..).
#    * End: Jump to the very last item in the folder.
#    * Prior (Page Up): Scroll up half a page and move highlight.
#    * Next (Page Down): Scroll down half a page and move highlight.
#
#   2. Selection (Marking Files)
#   These keys determine which files are "selected" for an operation.
#
#    * Space: Toggle selection of the current item and move highlight to the next one.
#    * Shift + Navigation: Select a range of items (e.g., Shift + Down selects multiple files).
#    * Control + Navigation: Select individual items without unselecting others.
#    * Escape: Clear all selections (unselect everything).
#
#   3. Execution (Opening/Menus)
#   These keys trigger the main interactions.
#
#    * Return (Enter): Open the highlighted item (enters a folder or runs xfilesctl open).
#    * Menu key: Open the context menu (runs xfilesctl menu).
#
#   4. Special "Passed" Keys (Sent to xfilesctl)
#   These keys do nothing inside the C code; instead, they are immediately sent to your xfilesctl script as strings (with a ^ prefix).
#
#    * Function Keys: F1 through F13 (sent as ^F1, ^F2, etc.).
#    * Editing Keys: Delete, BackSpace, Tab.
#    * Control + Any ASCII Key: Any combination like Ctrl+R, Ctrl+L, Ctrl+C, etc. (sent as ^r, ^l, ^c).

operation="$1"
# echo "$operation" > /tmp/key.txt
shift 1
for file
do
	shift 1
	case "$file" in
	("")
		# ignore empty arguments
		continue
		;;
	([!/]*)
		file="$PWD/$file"
		;;
	esac
	set -- "$@" "$file"
done
case "$operation" in
("menu"|^m)  # just 'm'
	case "$#" in
	(0)
		# right click on empty area; create a menu
		dirmenu "$@"
		;;
	(*)
		# right click on files; create a menu
		filemenu "$@"
		;;
	esac
	;;
("drop-ask")
	# droped something; create a menu
	dropmenu "$@"
	;;
("drop-copy")
	# copy dropped files here
	copy "$@"
	;;
("drop-move")
	# move dropped files here
	move "$@"
	;;
("drop-link")
	# link dropped files here
	link "$@"
	;;
(^minus|^BackSpace|^b)  # just 'b', just '-', just 'BackSpace' (BackSpace is default like this)
  if [ "$PWD" != "/" ]; then
    echo "$PWD" >> "$LOG_PREVS_DIRS"
    ndirs="$(wc -l < "$LOG_PREVS_DIRS")"
    if [ "$ndirs" -gt "$MAX_PREVS_DIRS" ]; then
      sed -i '1d' "$LOG_PREVS_DIRS"
    fi
  fi
	# go up
	changedir ".."
	;;
(^equal|^S-asciitilde|^d)  # just 'd'
  # go home
	changedir "$HOME"
	;;
# ADDED: (previous dir)
# TODO: why OLDPWD is not set?
# changedir "-" does not work
(^6)
 if [ -f "${LOG_PREV_DIR}" ]; then
   pwd >> "$LOG_PREVS_DIRS"
   ndirs="$(wc -l < "$LOG_PREVS_DIRS")"
   if [ "$ndirs" -gt "$MAX_PREVS_DIRS" ]; then
     sed -i '1d' "$LOG_PREVS_DIRS"
   fi
   changedir "$(cat "${LOG_PREV_DIR}")"
 fi
;;
(^f)  # just 'f'
  if [ -s "$LOG_PREVS_DIRS" ]; then
    last=$(tail -n 1 "$LOG_PREVS_DIRS")
    if [ -d "$last" ]; then
      changedir "$last"
      # remove last line
      sed -i '$d' "$LOG_PREVS_DIRS"
    fi
  fi
;;
(^F)
  findfiles "$@"
;;
# TODO: without xdotool?
(^p)  # just 'p'
  # scroll up
  xdotool click 4 &
	;;
# TODO: without xdotool?
(^n)  # just 'n'
  # scroll down
  xdotool click 5 &
	;;
(^F2|^R)
	# rename files on text editor
	rename "$@"
	;;
(^F5|^r)  # just 'r'
	# cd to where we are just to refresh
	changedir "."
	;;
(^w)  # just 'w'
  groot="$(git rev-parse --show-toplevel)"
  if [ -d "$groot" ]; then
    changedir "$groot"
  fi
  ;;
(^W)  # just 'W'
  # change to custom directory
  if [ -f "${LOG_CUSTOM_DIR}" ]; then
    changedir "$(cat "${LOG_CUSTOM_DIR}")"
  fi
  ;;
(^s)  # just 's'
  # set to custom directory
  pwd > "${LOG_CUSTOM_DIR}"
  ;;
(^slash)  # just '/'
	# open URL bar to go somewhere or open something
	urlbar
	;;
(^[Cc])
	# snarf files
	snarf "$@"
	;;
(^[Pp])
	# move snarfed files
	paste "mv"
	;;
(^[Vv])
	# copy snarfed files
	paste "cp"
	;;
(^Delete|^D)  # just 'Delete' (it's default like this)
	case "$PWD" in
	("$TRASH/files")
		# delete files from trash
		delete "$@"
		;;
	(*)
		# send files to trash
		trash "$@"
		;;
	esac
	;;
esac
